version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - miro-network

  miro_backend_api:
    build: ./Backend
    container_name: miro_backend_api
    ports:
      - "5002:5001"  # 🚀 Host port badal kar 5002 kar diya! Internal 5000 hi rahega
    environment:
      - MONGO_URI=mongodb://mongodb:27017/miro_db
    depends_on:
      - mongodb
    networks:
      - miro-network

  miro_frontend_client:
    build: ./Frontend
    container_name: miro_frontend_client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5002  # 🚀 Frontend ab backend ko 5002 par hit karega
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    networks:
      - miro-network

networks:
  miro-network:
    driver: bridge